[tasks.default]
  deps = [
    "git",
    "zsh",
    "tmux",
    "ruby",
    "emacs",
    "bin",
  ]

[tasks.git]
  links = [
    [".gitconfig"],
    [".gitignore_global"],
  ]

[tasks.zsh]
  links = [
    [".zshrc"],
    [".zshenv"],
    [".oh-my-zsh-custom"],
  ]

[tasks.tmux]
  links = [
    [".tmux.conf"]
  ]

[tasks.ruby]
  links = [
    [".irbrc"]
  ]

[tasks.emacs]
  links = [
    [".emacs"],
    [".emacs.d/Cask"],
    [".emacs.d/custom/"],
  ]

[tasks.bin]
  links = [
    ["bin/gitopener"],
  ]
