[tasks.default]
  deps = [
    "git",
    "zsh",
    "tmux",
    "emacs",
  ]

[tasks.git]
  links = [
    [".gitconfig"]
  ]

[tasks.zsh]
  links = [
    [".zshrc"],
    [".oh-my-zsh-custom"],
  ]

[tasks.tmux]
  links = [
    [".tmux.conf"]
  ]

[tasks.emacs]
  links = [
    [".emacs"],
    [".emacs.d/Cask"],
    [".emacs.d/custom/"],
  ]
